### ISSUE TITLE
Add command to toggle mask on and off

### ISSUE THREAD

**Issue by ljubadr** [ctf0/symbol-masks#2]
Thanks for this great extension!

Could you add option to toggle extension on and off?

I added some masks for php that make it easier when I'm reading a lot of code but I find it less useful when I'm writing code

**Comment by ctf0** [comment]
sure, will see what i can do

**Comment by ctf0** [comment]
check latest version, thanks.

**Comment by ljubadr** [comment]
It works perfectly! Thanks a lot
